export const arabicLabels = {
  Dashboard: "لوحة التحكم",
  Checkins: "تسجيل الحضور",
  Appointments: "المواعيد",
  "Appointment-Status-Log": "سجل حالات المواعيد",
  "Appointments-Calender": "تقويم المواعيد",
  Transactions: "المعاملات",
  Departments: "الأقسام",
  Specialization: "التخصصات",
  Doctors: "الأطباء",
  Patients: "المرضى",
  Users: "المستخدمون",
  Prescriptions: "الوصفات الطبية",
  "Patient-Files": "ملفات المرضى",
  Medicines: "الأدوية",
  "Family-Members": "أفراد العائلة",
  Coupons: "الكوبونات",
  "Doctor-Reviews": "تقييمات الأطباء",
  "Contact-Us-Form": "رسائل التواصل",
  Notification: "الإشعارات",
  Testimonials: "آراء العملاء",
  "Login-Screen": "شاشة تسجيل الدخول",
  Roles: "الأدوار",
  Settings: "الإعدادات",
  Account: "الحساب",
  "Change Password": "تغيير كلمة المرور",
  Logout: "تسجيل الخروج",
  Search: "بحث",
  Action: "الإجراء",
  "No data found": "لا توجد بيانات",
  "No data available in table": "لا توجد بيانات في الجدول",
  "N/A": "غير متاح",
  "Sign in to your account": "تسجيل الدخول إلى حسابك",
  Email: "البريد الإلكتروني",
  Password: "كلمة المرور",
  "Enter password": "أدخل كلمة المرور",
  "Forget password?": "نسيت كلمة المرور؟",
  "Sign in": "تسجيل الدخول",
  "Login As -": "تسجيل الدخول كـ",
  Continue: "متابعة",
  Cancel: "إلغاء",
  Close: "إغلاق",
  Update: "تحديث",
  "First Name": "الاسم الأول",
  Name: "الاسم",
  Phone: "رقم الهاتف",
  "Member Since": "عضو منذ",
  "Login Success.": "تم تسجيل الدخول بنجاح.",
  "Wrong Email Or Password.": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "An error occurred during login. Please try again.":
    "حدث خطأ أثناء تسجيل الدخول. حاول مرة أخرى.",
  "You do not have permission to access the admin panel. Please contact the administrator if you believe this is an error.":
    "ليس لديك صلاحية للوصول إلى لوحة الإدارة. يرجى التواصل مع المسؤول إذا كنت تعتقد أن هذا خطأ.",
  updated: "تم التحديث",
  "updated!": "تم التحديث!",
  "Oops!": "حدث خطأ!",
  "oops!": "حدث خطأ!",
  "oops!.": "حدث خطأ!",
  "You are not authorized": "غير مصرح لك",
  "Email Sent": "تم إرسال البريد الإلكتروني",
};

const phraseTranslations = {
  "Add New": "إضافة جديد",
  "Add": "إضافة",
  "Edit": "تعديل",
  "Delete": "حذف",
  "View": "عرض",
  "Details": "التفاصيل",
  "Save": "حفظ",
  "Submit": "إرسال",
  "Back": "رجوع",
  "Next": "التالي",
  "Previous": "السابق",
  "Print": "طباعة",
  "Download": "تنزيل",
  "Upload": "رفع",
  "Choose File": "اختر ملف",
  "Choose a file": "اختر ملفًا",
  "or Drag it here.": "أو اسحبه هنا.",
  "Image": "الصورة",
  "File": "الملف",
  "File Name": "اسم الملف",
  "Body": "المحتوى",
  "Status": "الحالة",
  "Active": "نشط",
  "Inactive": "غير نشط",
  "Pending": "قيد الانتظار",
  "Approved": "مقبول",
  "Rejected": "مرفوض",
  "Completed": "مكتمل",
  "Cancelled": "ملغي",
  "Confirmed": "مؤكد",
  "Visited": "تمت الزيارة",
  "Cancellation": "طلب إلغاء",
  "Cancellation Initiated": "تم بدء طلب الإلغاء",
  "Cancellation Req Initiated": "طلبات الإلغاء الجديدة",
  "Cancellation Request Processing": "طلبات الإلغاء قيد المعالجة",
  "Cancellation Request Approved": "طلبات الإلغاء المقبولة",
  "Cancellation Request Rejected": "طلبات الإلغاء المرفوضة",
  "Paid": "مدفوع",
  "Unpaid": "غير مدفوع",
  "Not Paid": "غير مدفوع",
  "Refunded": "تم رد المبلغ",
  "Online": "أونلاين",
  "Offline": "أوفلاين",
  "Cash": "نقدًا",
  "Card": "بطاقة",
  "UPI": "UPI",
  "Today": "اليوم",
  "Today's Appointment": "مواعيد اليوم",
  "Upcoming Appointment": "المواعيد القادمة",
  "Pending Appointments": "المواعيد قيد الانتظار",
  "Confirm Appointments": "المواعيد المؤكدة",
  "Cancelled Appointments": "المواعيد الملغاة",
  "Rejected Appointments": "المواعيد المرفوضة",
  "Completed Appointments": "المواعيد المكتملة",
  "Visited Appointments": "المواعيد التي تمت زيارتها",
  "This Month": "هذا الشهر",
  "This Year": "هذا العام",
  "From": "من",
  "To": "إلى",
  "Date": "التاريخ",
  "Time": "الوقت",
  "Created At": "تاريخ الإنشاء",
  "Updated At": "تاريخ التحديث",
  "Created at": "تاريخ الإنشاء",
  "Updated at": "تاريخ التحديث",
  "ID": "المعرف",
  "Id": "المعرف",
  "S No.": "م",
  "Appointment ID": "معرف الموعد",
  "User": "المستخدم",
  "User Notification": "إشعارات المستخدمين",
  "Doctor Notification": "إشعارات الأطباء",
  "Admin Notification": "إشعارات الإدارة",
  "Doctor": "الطبيب",
  "Doctor Details": "بيانات الطبيب",
  "Doctor Details ": "بيانات الطبيب",
  "Patient": "المريض",
  "Patient Name": "اسم المريض",
  "Patient Files": "ملفات المريض",
  "Patient Appointments": "مواعيد المريض",
  "Department": "القسم",
  "Specialization": "التخصص",
  "Appointment": "الموعد",
  "Transaction": "المعاملة",
  "Payment": "الدفع",
  "Payment Method": "طريقة الدفع",
  "All Transactions": "كل المعاملات",
  "Appointment Payments": "مدفوعات المواعيد",
  "Invoice": "الفاتورة",
  "Invoices": "الفواتير",
  "Prescription": "الوصفة الطبية",
  "Patient Prescriptions": "وصفات المريض",
  "Medicine": "الدواء",
  "Add New Medicine": "إضافة دواء جديد",
  "Update Medicine": "تحديث الدواء",
  "Coupon": "الكوبون",
  "All Coupons": "كل الكوبونات",
  "Used Coupons": "الكوبونات المستخدمة",
  "Role": "الدور",
  "Assigned users": "المستخدمون المسندون",
  "Permission": "الصلاحية",
  "Permissoins": "الصلاحيات",
  "Permissions": "الصلاحيات",
  "City": "المدينة",
  "State": "المحافظة",
  "Country": "الدولة",
  "Address": "العنوان",
  "Gender": "النوع",
  "Male": "ذكر",
  "Female": "أنثى",
  "Age": "العمر",
  "DOB": "تاريخ الميلاد",
  "Date of Birth": "تاريخ الميلاد",
  "Date Of Birth": "تاريخ الميلاد",
  "Date Of Birth (MM/DD/YYYY)": "تاريخ الميلاد (شهر/يوم/سنة)",
  "Blood Group": "فصيلة الدم",
  "Description": "الوصف",
  "Title": "العنوان",
  "Sub Title": "العنوان الفرعي",
  "Page Title": "عنوان الصفحة",
  "Message": "الرسالة",
  "Subject": "الموضوع",
  "URL": "الرابط",
  "Key": "المفتاح",
  "Secret": "السر",
  "Webhook Secret Key": "مفتاح سر Webhook",
  "Value": "القيمة",
  "Fee": "الرسوم",
  "Service Charge": "رسوم الخدمة",
  "Rating": "التقييم",
  "Notes": "ملاحظات",
  "Type": "النوع",
  "Amount": "المبلغ",
  "Enter amount": "أدخل المبلغ",
  "Enter description (e.g., Amount credited to user wallet)":
    "أدخل الوصف (مثال: إضافة مبلغ إلى محفظة المستخدم)",
  "Price": "السعر",
  "Fees": "الرسوم",
  "Discount": "الخصم",
  "Total": "الإجمالي",
  "Sub Total": "الإجمالي الفرعي",
  "Start Time": "وقت البداية",
  "End Time": "وقت النهاية",
  "Start Date": "تاريخ البداية",
  "End Date": "تاريخ النهاية",
  "Time Duration": "مدة الوقت",
  "Time Slotes": "الأوقات المتاحة",
  "Available": "متاح",
  "Unavailable": "غير متاح",
  "Select": "اختر",
  "Select Doctor": "اختر الطبيب",
  "Select Patient": "اختر المريض",
  "Select Department": "اختر القسم",
  "Select Status": "اختر الحالة",
  "Select Date": "اختر التاريخ",
  "Select Role": "اختر الدور",
  "Select Gender": "اختر النوع",
  "Select Day": "اختر اليوم",
  "Select paymemnt status": "اختر حالة الدفع",
  "Select paymemnt Method": "اختر طريقة الدفع",
  "Select payment method": "اختر طريقة الدفع",
  "Are you sure?": "هل أنت متأكد؟",
  "Confirm": "تأكيد",
  "Yes": "نعم",
  "No": "لا",
  "Loading": "جاري التحميل",
  "Failed to load appointments": "فشل تحميل المواعيد",
  "Error loading data": "حدث خطأ أثناء تحميل البيانات",
  "Success": "نجاح",
  "Error": "خطأ",
  "Required": "مطلوب",
  "Optional": "اختياري",
  "Profile": "الملف الشخصي",
  "Profile Picture": "الصورة الشخصية",
  "Overview": "نظرة عامة",
  "Reviews": "التقييمات",
  "Payments": "المدفوعات",
  "Family Members": "أفراد العائلة",
  "Family Vitals Data": "القياسات الحيوية للعائلة",
  "Wallet": "المحفظة",
  "Web pages": "صفحات الموقع",
  "Social Media": "وسائل التواصل الاجتماعي",
  "Payment Getways": "بوابات الدفع",
  "Welcome Back!": "مرحبًا بعودتك!",
  "Appointment Status Distribution": "توزيع حالات المواعيد",
  "Transaction Total Amount Distribution": "توزيع إجمالي مبالغ المعاملات",
  "All": "الكل",
  "Password": "كلمة المرور",
  "Old Password": "كلمة المرور القديمة",
  "New Password": "كلمة المرور الجديدة",
  "Confirm Password": "تأكيد كلمة المرور",
  "Confirm New Password": "تأكيد كلمة المرور الجديدة",
  "Current Password": "كلمة المرور الحالية",
  "Reset Password": "إعادة تعيين كلمة المرور",
  "Forgot Password": "نسيت كلمة المرور",
  "Cnf Password": "تأكيد كلمة المرور",
  "CNF Password": "تأكيد كلمة المرور",
  "Enter Old password": "أدخل كلمة المرور القديمة",
  "Enter new password": "أدخل كلمة المرور الجديدة",
  "Confirm new password": "أكد كلمة المرور الجديدة",
  "Hide password": "إخفاء كلمة المرور",
  "Show password": "إظهار كلمة المرور",
  "Phone Number": "رقم الهاتف",
  "phone Number": "رقم الهاتف",
  "Enter your phone number": "أدخل رقم الهاتف",
  "Postal Code": "الرمز البريدي",
  "Years OF Experience": "سنوات الخبرة",
  "OPD Fee": "رسوم الكشف",
  "Video Fee": "رسوم الاستشارة بالفيديو",
  "Emergency Fee": "رسوم الطوارئ",
  "Blood Pressure": "ضغط الدم",
  "Blood Suger": "سكر الدم",
  "Blood Sugar": "سكر الدم",
  "Spo2": "نسبة الأكسجين",
  "Tempature": "درجة الحرارة",
  "Temperature": "درجة الحرارة",
  "Weight": "الوزن",
  "Pulse Rate": "معدل النبض",
  "Food Allergies": "حساسية الطعام",
  "Tendency to Bleed": "قابلية النزيف",
  "Heart Disease": "أمراض القلب",
  "Diabetic": "السكري",
  "Surgery": "عمليات جراحية",
  "Accident": "حادث",
  "Others": "أخرى",
  "Medical History": "التاريخ المرضي",
  "Current Medication": "الأدوية الحالية",
  "Female Pregnancy": "حمل",
  "Breast Feeding": "رضاعة طبيعية",
  "After Meal": "بعد الأكل",
  "Before Meal": "قبل الأكل",
  "Once a Day": "مرة يوميًا",
  "For 3 days": "لمدة 3 أيام",
  "For 5 days": "لمدة 5 أيام",
  "For 7 days": "لمدة 7 أيام",
  "for 7 days": "لمدة 7 أيام",
  "for 15 days": "لمدة 15 يومًا",
  "for 1 Month": "لمدة شهر",
  "No upcoming patients": "لا يوجد مرضى قادمون",
  "No patient is currently being seen": "لا يوجد مريض يتم الكشف عليه حاليًا",
  "Search reviews": "البحث في التقييمات",
  "Search permissions...": "البحث في الصلاحيات...",
  "Enter your email": "أدخل بريدك الإلكتروني",
  "Enter systolic pressure": "أدخل الضغط الانقباضي",
  "Enter diastolic pressure": "أدخل الضغط الانبساطي",
  "Enter Weight (KG)": "أدخل الوزن (كجم)",
  "Enter Temperature (°C)": "أدخل درجة الحرارة (°C)",
  "Enter Fasting Blood sugar": "أدخل سكر الدم الصائم",
  "Enter Random Blood sugar": "أدخل سكر الدم العشوائي",
  "Enter SpO2 (%)": "أدخل نسبة الأكسجين (%)",
  "Enter spo2 (%)": "أدخل نسبة الأكسجين (%)",
  "3 Times a day": "3 مرات يوميًا",
  "4 Times a day": "4 مرات يوميًا",
  "Add Appointment": "إضافة موعد",
  "Add Blood Pressure Data": "إضافة بيانات ضغط الدم",
  "Add Blood Sugar Data": "إضافة بيانات سكر الدم",
  "Add Checkin": "إضافة تسجيل حضور",
  "Add City": "إضافة مدينة",
  "Add Coupon": "إضافة كوبون",
  "Add Data": "إضافة بيانات",
  "Add Data Manually": "إضافة البيانات يدويًا",
  "Add Department": "إضافة قسم",
  "Add Doctor": "إضافة طبيب",
  "Add Family Member": "إضافة فرد عائلة",
  "Add File": "إضافة ملف",
  "Add Login Image": "إضافة صورة تسجيل الدخول",
  "Add Login Screen Image": "إضافة صورة شاشة تسجيل الدخول",
  "Add Medicine": "إضافة دواء",
  "Add patient": "إضافة مريض",
  "Add Patient": "إضافة مريض",
  "Add Patient Files": "إضافة ملفات مريض",
  "Add Prescription": "إضافة وصفة طبية",
  "Add Secial Media": "إضافة وسيلة تواصل",
  "Add Slot": "إضافة وقت",
  "Add Specialization": "إضافة تخصص",
  "Add SpO2 Data": "إضافة بيانات الأكسجين",
  "Add State": "إضافة محافظة",
  "Add Temperature Data": "إضافة بيانات درجة الحرارة",
  "Add Testimonial": "إضافة رأي عميل",
  "Add Time Slot": "إضافة موعد متاح",
  "Add User": "إضافة مستخدم",
  "Add Video Time Slot": "إضافة موعد فيديو متاح",
  "Add Weight Data": "إضافة بيانات الوزن",
  "Added!": "تمت الإضافة!",
  "Advice": "النصيحة",
  "Advise": "النصيحة",
  "After": "بعد",
  "Amount Paid": "المبلغ المدفوع",
  "Appointment Calendar": "تقويم المواعيد",
  "Appointment Cancellation Status": "حالة إلغاء الموعد",
  "Appointment Date": "تاريخ الموعد",
  "Appointment not found": "الموعد غير موجود",
  "Appointment Time Slot": "وقت الموعد",
  "Appointment Type": "نوع الموعد",
  "Are you sure? You can not undo this action afterwards.":
    "هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء بعد ذلك.",
  "Assign Role": "تعيين دور",
  "Assign Role To User": "تعيين دور للمستخدم",
  "Basic Details": "البيانات الأساسية",
  "Blood Pressure History": "سجل ضغط الدم",
  "Blood Sugar History": "سجل سكر الدم",
  "Cancellation Req By Patient": "طلب الإلغاء من المريض",
  "Cannot Delete This Role!": "لا يمكن حذف هذا الدور!",
  "Change Profile Picture": "تغيير الصورة الشخصية",
  "Choose Region": "اختر المنطقة",
  "City Added!": "تمت إضافة المدينة!",
  "City Deleted!": "تم حذف المدينة!",
  "City Updated!": "تم تحديث المدينة!",
  "Contact Details": "بيانات التواصل",
  "Contact Inquiry": "استفسار تواصل",
  "Coupon Added!": "تمت إضافة الكوبون!",
  "Coupon Deleted!": "تم حذف الكوبون!",
  "Coupon Updated!": "تم تحديث الكوبون!",
  "Created At:": "تاريخ الإنشاء:",
  "Credited": "دائن",
  "Day": "اليوم",
  "Days": "الأيام",
  "Debited": "مدين",
  "Delete Assign Role": "حذف الدور المسند",
  "Delete City": "حذف المدينة",
  "Delete Contact": "حذف رسالة التواصل",
  "Delete Coupon": "حذف الكوبون",
  "Delete Department": "حذف القسم",
  "Delete Doctor": "حذف الطبيب",
  "Delete Family Member": "حذف فرد العائلة",
  "Delete File": "حذف الملف",
  "Delete Login Page Image": "حذف صورة صفحة تسجيل الدخول",
  "Delete Medicine": "حذف الدواء",
  "Delete Prescription": "حذف الوصفة الطبية",
  "Delete Role": "حذف الدور",
  "Delete Specialization": "حذف التخصص",
  "Delete State": "حذف المحافظة",
  "Delete Testimonial": "حذف رأي العميل",
  "Delete Vitals Data": "حذف بيانات القياسات الحيوية",
  "Deleted!": "تم الحذف!",
  "Department Added!": "تمت إضافة القسم!",
  "Department Deleted!": "تم حذف القسم!",
  "Department Updated!": "تم تحديث القسم!",
  "Diastolic": "الانبساطي",
  "Diastolic (mmHg)": "الانبساطي (mmHg)",
  "Doctor Active ?": "هل الطبيب نشط؟",
  "Doctor Added!": "تمت إضافة الطبيب!",
  "Doctor Deleted!": "تم حذف الطبيب!",
  "Doctor First Name": "الاسم الأول للطبيب",
  "Doctor Last Name": "اسم عائلة الطبيب",
  "Doctor Reviews": "تقييمات الطبيب",
  "Doctor Specialization": "تخصص الطبيب",
  "Doctor Updated!": "تم تحديث الطبيب!",
  "Doctor Updateddddd!": "تم تحديث الطبيب!",
  "Dosage": "الجرعة",
  "Dose Interval": "الفاصل بين الجرعات",
  "Duration": "المدة",
  "Education And Other Deta": "التعليم وبيانات أخرى",
  "Email your email address": "أدخل بريدك الإلكتروني",
  "Email:": "البريد الإلكتروني:",
  "Error Illustration": "صورة الخطأ",
  "Every Morning & Evening": "كل صباح ومساء",
  "Family Member Added!": "تمت إضافة فرد العائلة!",
  "Family Member Deleted!": "تم حذف فرد العائلة!",
  "Family Member Updated!": "تم تحديث فرد العائلة!",
  "Family Vitals Details": "تفاصيل القياسات الحيوية للعائلة",
  "Fasting": "صائم",
  "Fasting (Mg/dl)": "صائم (Mg/dl)",
  "File Added!": "تمت إضافة الملف!",
  "Filter": "تصفية",
  "Get Details": "جلب التفاصيل",
  "Go to Appointment": "الذهاب إلى الموعد",
  "Go to File": "الذهاب إلى الملف",
  "Go to Prescription": "الذهاب إلى الوصفة",
  "Go to User": "الذهاب إلى المستخدم",
  "Image deleted!": "تم حذف الصورة!",
  "Image Deleted!": "تم حذف الصورة!",
  "Insert New Medicine": "إدخال دواء جديد",
  "Internal Server Error": "خطأ داخلي في الخادم",
  "Is Active": "نشط",
  "Join Meeting": "الانضمام للاجتماع",
  "Last Name": "اسم العائلة",
  "Max 5 MB": "الحد الأقصى 5 ميجابايت",
  "Medicine Added!": "تمت إضافة الدواء!",
  "Medicines": "الأدوية",
  "Meeting ID": "معرف الاجتماع",
  "Message:": "الرسالة:",
  "New checkin": "تسجيل حضور جديد",
  "New Checkin": "تسجيل حضور جديد",
  "New Medicine": "دواء جديد",
  "New Prescription": "وصفة طبية جديدة",
  "Next Patients": "المرضى التاليون",
  "Next Visit": "الزيارة القادمة",
  "No Data Found": "لا توجد بيانات",
  "No notifications": "لا توجد إشعارات",
  "Notes Tooltip": "ملاحظات",
  "Notification sent!": "تم إرسال الإشعار!",
  "Notifications": "الإشعارات",
  "Now": "الآن",
  "Oops! Something went wrong on our end. We are currently working on fixing the issue.":
    "حدث خطأ من جانبنا. نعمل حاليًا على حل المشكلة.",
  "Or": "أو",
  "Other": "أخرى",
  "password does not match": "كلمة المرور غير متطابقة",
  "Patient Added": "تمت إضافة المريض",
  "Patient Details": "بيانات المريض",
  "Patient File Deleted": "تم حذف ملف المريض",
  "Patient File Updated!": "تم تحديث ملف المريض!",
  "Patient First Name": "الاسم الأول للمريض",
  "Patient Last Name": "اسم عائلة المريض",
  "Patient Updated!": "تم تحديث المريض!",
  "Patients Details": "بيانات المرضى",
  "Payment getway updated!": "تم تحديث بوابة الدفع!",
  "Payment Id": "معرف الدفع",
  "Payment Status": "حالة الدفع",
  "Permissions Updated": "تم تحديث الصلاحيات",
  "Physical Details": "البيانات الجسدية",
  "Physical Information": "المعلومات الجسدية",
  "Please contact your administrator if you believe this is a mistake.":
    "يرجى التواصل مع المسؤول إذا كنت تعتقد أن هذا خطأ.",
  "Please fill all the medicine details": "يرجى إدخال كل بيانات الدواء",
  "Please select a file smaller than 5 MB.":
    "يرجى اختيار ملف أقل من 5 ميجابايت.",
  "Please Select Appointment Type": "يرجى اختيار نوع الموعد",
  "Please Select Doctor": "يرجى اختيار الطبيب",
  "Please Select Family Member": "يرجى اختيار فرد العائلة",
  "Please Select File": "يرجى اختيار ملف",
  "Please Select Patient": "يرجى اختيار المريض",
  "Please Select Payment Mode": "يرجى اختيار طريقة الدفع",
  "Please Select User": "يرجى اختيار المستخدم",
  "Please try refreshing the page, or you can return to the homepage.":
    "يرجى تحديث الصفحة، أو الرجوع إلى الصفحة الرئيسية.",
  "Please Update the Cancellation request first": "يرجى تحديث طلب الإلغاء أولًا",
  "Prescription Deleted!": "تم حذف الوصفة الطبية!",
  "Print Consultation Report": "طباعة تقرير الاستشارة",
  "Problem": "المشكلة",
  "Problem & Advice": "المشكلة والنصيحة",
  "Random": "عشوائي",
  "Random (Mg/dl)": "عشوائي (Mg/dl)",
  "Recharge Wallet": "شحن المحفظة",
  "Refresh": "تحديث",
  "Refresh Table": "تحديث الجدول",
  "Reject": "رفض",
  "Remove Image": "حذف الصورة",
  "Reschedule Appointment": "إعادة جدولة الموعد",
  "Role Added!": "تمت إضافة الدور!",
  "Role Deleted!": "تم حذف الدور!",
  "Role Updated!": "تم تحديث الدور!",
  "Scan QR": "مسح QR",
  "Search country name , code": "ابحث باسم الدولة أو الكود",
  "Secondary Phone": "رقم الهاتف الإضافي",
  "Select date and Time Slot": "اختر التاريخ والوقت",
  "Select Date Range": "اختر نطاق التاريخ",
  "Select ISD Code": "اختر كود الدولة",
  "select specialization": "اختر التخصص",
  "Select User": "اختر المستخدم",
  "Sent Notification": "إرسال إشعار",
  "Sent User Notification": "إرسال إشعار للمستخدم",
  "Set": "تطبيق",
  "Set Amount to Paid": "تعيين المبلغ كمدفوع",
  "Show Checkin Display": "عرض شاشة الحضور",
  "Social Media Added!": "تمت إضافة وسيلة التواصل!",
  "Social Media Deleted!": "تم حذف وسيلة التواصل!",
  "Social Media Updated!": "تم تحديث وسيلة التواصل!",
  "Sorry , no available time slotes ware found for the selected date.":
    "عذرًا، لا توجد مواعيد متاحة في التاريخ المحدد.",
  "Specialization Added!": "تمت إضافة التخصص!",
  "Specialization Deleted!": "تم حذف التخصص!",
  "Specialization Updated!": "تم تحديث التخصص!",
  "SpO2 (%)": "نسبة الأكسجين (%)",
  "SpO2 History": "سجل نسبة الأكسجين",
  "State Added!": "تمت إضافة المحافظة!",
  "State Deleted!": "تم حذف المحافظة!",
  "State Updated!": "تم تحديث المحافظة!",
  "Stop Booking ?": "إيقاف الحجز؟",
  "Subject:": "الموضوع:",
  "Success!": "تم بنجاح!",
  "Systolic": "الانقباضي",
  "Systolic (mmHg)": "الانقباضي (mmHg)",
  "Temp (°C)": "درجة الحرارة (°C)",
  "Temperature (°C)": "درجة الحرارة (°C)",
  "Temperature History": "سجل درجة الحرارة",
  "Test": "الاختبارات",
  "testimonial Added!": "تمت إضافة رأي العميل!",
  "Testimonial Deleted!": "تم حذف رأي العميل!",
  "Testimonial Updated!": "تم تحديث رأي العميل!",
  "Tests": "الاختبارات",
  "This is not a valid url": "هذا الرابط غير صالح",
  "Time Duration ( In Minutes )": "مدة الوقت (بالدقائق)",
  "Time Slot Added!": "تمت إضافة الموعد المتاح!",
  "Time Slot Added!sssssssss": "تمت إضافة الموعد المتاح!",
  "Time Slot Deleted!": "تم حذف الموعد المتاح!",
  "Toggle color mode": "تبديل وضع الألوان",
  "Total Active Doctors": "إجمالي الأطباء النشطين",
  "Total Amount": "الإجمالي",
  "Total Appointments": "إجمالي المواعيد",
  "Total Departments": "إجمالي الأقسام",
  "Total Medicine": "إجمالي الأدوية",
  "Total Patients": "إجمالي المرضى",
  "Total Prescriptions": "إجمالي الوصفات الطبية",
  "Total Users": "إجمالي المستخدمين",
  "Try Again": "حاول مرة أخرى",
  "Update Blood Pressure Data": "تحديث بيانات ضغط الدم",
  "Update Blood Sugar Data": "تحديث بيانات سكر الدم",
  "Update Checkin": "تحديث تسجيل الحضور",
  "Update City": "تحديث المدينة",
  "Update Coupon": "تحديث الكوبون",
  "Update Department": "تحديث القسم",
  "Update Family Member": "تحديث فرد العائلة",
  "Update Fees": "تحديث الرسوم",
  "Update Patient Files": "تحديث ملفات المريض",
  "Update Payment Getways": "تحديث بوابات الدفع",
  "Update Permissions": "تحديث الصلاحيات",
  "Update Prescription": "تحديث الوصفة الطبية",
  "Update Request Status": "تحديث حالة الطلب",
  "Update Role": "تحديث الدور",
  "Update Social Media": "تحديث وسائل التواصل",
  "Update Specialization": "تحديث التخصص",
  "Update SpO2 Data": "تحديث بيانات الأكسجين",
  "Update State": "تحديث المحافظة",
  "Update Temperature Data": "تحديث بيانات درجة الحرارة",
  "Update Testimonials": "تحديث آراء العملاء",
  "Update Title": "تحديث العنوان",
  "Update Weight Data": "تحديث بيانات الوزن",
  "Updated!": "تم التحديث!",
  "Upload Profile Picture": "رفع الصورة الشخصية",
  "User Added!": "تمت إضافة المستخدم!",
  "User Updated!": "تم تحديث المستخدم!",
  "Value ( Off in %)": "القيمة (خصم بالنسبة المئوية)",
  "Video Consultations cannot be checked in":
    "لا يمكن تسجيل حضور استشارات الفيديو",
  "Weight (KG)": "الوزن (كجم)",
  "Weight History": "سجل الوزن",
  "You tried to access a page you do not have permission to view.":
    "حاولت الوصول إلى صفحة لا تملك صلاحية عرضها.",
  "APP ID": "معرف التطبيق",
  "app ID": "معرف التطبيق",
  "OPD": "كشف عيادة",
  "Facebook": "فيسبوك",
  "Instagram": "إنستجرام",
  "Twitter": "تويتر",
  "Youtube": "يوتيوب",
  "OPD timeslot ?": "موعد عيادة؟",
  "video timeslot ?": "موعد فيديو؟",
  "Ex: https://www.facebook.com": "مثال: https://www.facebook.com",
  "Monday": "الإثنين",
  "Tuesday": "الثلاثاء",
  "Wednesday": "الأربعاء",
  "Thursday": "الخميس",
  "Friday": "الجمعة",
  "Saturday": "السبت",
  "Sunday": "الأحد",
};

export const translations = {
  ...arabicLabels,
  ...phraseTranslations,
};

export function translateLabel(value) {
  if (value === null || value === undefined) return value;
  const text = String(value).replace(/_/g, " ").trim();
  if (!text) return value;

  const compactRoute = text
    .split("/")
    .filter(Boolean)
    .pop();
  const normalized = (compactRoute || text)
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("-");

  const translated =
    translations[text] ||
    translations[normalized] ||
    translations[
      text
        .split(" ")
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(" ")
    ];

  if (translated) return translated;

  const trailingMatch = text.match(/^(.+?)(\s*[:\-؟?]+)$/);
  if (trailingMatch) {
    const baseTranslation = translateLabel(trailingMatch[1]);
    if (baseTranslation !== trailingMatch[1]) {
      return `${baseTranslation}${trailingMatch[2]}`;
    }
  }

  const parenthesizedMatch = text.match(/^(.+?)\s*\((.*)$/);
  if (parenthesizedMatch) {
    const baseTranslation = translateLabel(parenthesizedMatch[1]);
    if (baseTranslation !== parenthesizedMatch[1]) {
      return `${baseTranslation} (${parenthesizedMatch[2]}`;
    }
  }

  const selectMatch = text.match(/^(Select|Search|Add|Update|Delete|No)\s+(.+?)(\s+found\.)?$/i);
  if (selectMatch) {
    const action = translateLabel(
      selectMatch[1].charAt(0).toUpperCase() + selectMatch[1].slice(1).toLowerCase()
    );
    const target = translateLabel(selectMatch[2]);
    if (selectMatch[1].toLowerCase() === "no" && selectMatch[3]) {
      return `لا يوجد ${target}`;
    }
    if (action !== selectMatch[1] || target !== selectMatch[2]) {
      return `${action} ${target}`;
    }
  }

  return text;
}

const shouldSkipNode = (node) => {
  const parent = node.parentElement;
  if (!parent) return true;
  return ["SCRIPT", "STYLE", "TEXTAREA", "CODE", "PRE"].includes(
    parent.tagName
  );
};

function translateTextNode(node) {
  if (shouldSkipNode(node)) return;
  const original = node.nodeValue;
  const trimmed = original.trim();
  if (!trimmed || /[\u0600-\u06FF]/.test(trimmed)) return;
  const translated = translateLabel(trimmed);
  if (translated !== trimmed) {
    node.nodeValue = original.replace(trimmed, translated);
  }
}

function translateElementAttributes(element) {
  ["placeholder", "aria-label", "title", "alt"].forEach((attr) => {
    const value = element.getAttribute(attr);
    if (!value || /[\u0600-\u06FF]/.test(value)) return;
    const translated = translateLabel(value);
    if (translated !== value) element.setAttribute(attr, translated);
  });
}

function translateNode(node) {
  if (node.nodeType === Node.TEXT_NODE) {
    translateTextNode(node);
    return;
  }

  if (node.nodeType !== Node.ELEMENT_NODE) return;

  translateElementAttributes(node);
  node.childNodes.forEach(translateNode);
}

export function applyArabicTranslations() {
  if (typeof document === "undefined") return;

  document.documentElement.lang = "ar";
  document.documentElement.dir = "rtl";
  document.body.dir = "rtl";
  translateNode(document.body);

  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      mutation.addedNodes.forEach(translateNode);
      if (mutation.type === "characterData") translateTextNode(mutation.target);
      if (mutation.type === "attributes") translateElementAttributes(mutation.target);
    });
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    characterData: true,
    attributes: true,
    attributeFilter: ["placeholder", "aria-label", "title", "alt"],
  });
}
